version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
  AfterInstall:
    - location: scripts/migrate.sh
      timeout: 180